# Generated by Django 2.2.6 on 2019-10-24 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountsmodel',
            name='value',
        ),
    ]
