# Generated by Django 2.2.6 on 2019-10-24 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyApp', '0004_auto_20191024_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionmodel',
            name='assignment',
            field=models.ForeignKey(blank=True, limit_choices_to={'parent': False}, null=True, on_delete=django.db.models.deletion.CASCADE, to='CompanyApp.AssignmentModel'),
        ),
    ]
