# Generated by Django 2.2.6 on 2019-10-24 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyApp', '0005_transactionmodel_assignment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TransactionModel',
        ),
    ]
