# Generated by Django 2.2.6 on 2019-10-24 07:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyApp', '0006_delete_transactionmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('XERC', 'Xerc'), ('GELIR', 'Gelir'), ('BORC', 'Borc')], max_length=10)),
                ('date', models.DateField(default=datetime.date(2019, 10, 24))),
                ('currency', models.CharField(choices=[('AZN', 'Azn'), ('EUR', 'Eur'), ('USD', 'Usd')], max_length=4)),
                ('value', models.FloatField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='CompanyApp.AccountsModel')),
                ('assignment', models.ForeignKey(limit_choices_to={'parent': False}, on_delete=django.db.models.deletion.CASCADE, to='CompanyApp.AssignmentModel')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CompanyApp.CompanyModel')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CompanyApp.CustomerModel')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CompanyApp.PersonsModel')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CompanyApp.ProjectsModel')),
            ],
        ),
    ]
