# Generated by Django 2.2.6 on 2019-10-24 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyApp', '0007_transactionmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsmodel',
            name='azn_value',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='accountsmodel',
            name='value',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='transactionmodel',
            name='azn_value',
            field=models.FloatField(default=0),
        ),
    ]
