# Generated by Django 2.2.6 on 2019-10-24 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyApp', '0008_auto_20191024_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionmodel',
            name='currency',
            field=models.CharField(choices=[('AZN', 'AZN'), ('EUR', 'EUR'), ('USD', 'USD')], max_length=4),
        ),
    ]
