# Generated by Django 2.2.6 on 2019-10-24 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyApp', '0009_auto_20191024_0724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountsmodel',
            name='azn_value',
        ),
        migrations.RemoveField(
            model_name='accountsmodel',
            name='value',
        ),
    ]
