# Generated by Django 2.2.6 on 2019-10-24 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyApp', '0010_auto_20191024_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsmodel',
            name='azn_val',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='transactionmodel',
            name='assignment',
            field=models.ForeignKey(limit_choices_to={'parent': False}, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='CompanyApp.AssignmentModel'),
        ),
        migrations.AlterField(
            model_name='transactionmodel',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='CompanyApp.CustomerModel'),
        ),
        migrations.AlterField(
            model_name='transactionmodel',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='CompanyApp.PersonsModel'),
        ),
    ]
