# Generated by Django 2.2.6 on 2019-10-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyApp', '0011_auto_20191024_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsmodel',
            name='azn_val',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
