# Generated by Django 2.2.6 on 2019-10-24 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyApp', '0012_auto_20191024_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountsmodel',
            name='azn_val',
        ),
    ]
