# Generated by Django 2.2.6 on 2019-10-25 07:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyApp', '0013_remove_accountsmodel_azn_val'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsmodel',
            name='date',
            field=models.DateField(default=datetime.date(2019, 10, 25)),
        ),
        migrations.AlterField(
            model_name='transactionmodel',
            name='date',
            field=models.DateField(default=datetime.date(2019, 10, 25)),
        ),
        migrations.AlterField(
            model_name='transactionmodel',
            name='type',
            field=models.CharField(choices=[('Expense', 'expense'), ('Revenue', 'revenue'), ('Debt', 'debt')], max_length=10),
        ),
    ]
